### ISSUE TITLE
公开地理数据来源从哪里获取？

### ISSUE THREAD

**Issue by EDsoft2018** [SuperMap/SuperMap-iEarth#17]
作为国内唯一一家GIS龙头企业。能不能出一个数据来源的专题，
比如：各时期影像图，矢量图。本来就是网上公开的数据何必那么封锁。

**Comment by fishelren** [comment]
您好，您提出的意见我们正在讨论，能否留下您的联系方式，方便更细致地进行沟通~

**Comment by EDsoft2018** [comment]
感觉贵公司，对技术封锁有点严重，git一类的开源社区根本看不到身影，自己搭建的反馈平台，又三分钟热度。对于底层核心把控好，难道还不够吗？
Git，emill。本来就是一个交流沟通的方式？

**Comment by fishelren** [comment]
超图三维团队目前的很多数据也是经客户授权后才使用的，版权在客户，因此无法提供，望谅解~

**Comment by EDsoft2018** [comment]
https://malagis.com/category/gis-resource/


道理我都懂，有公开数据的，只是掌握在服务商手里，没有渠道

**Comment by HX1995** [comment]
超图的开源iearth也是开的很封闭，哎，数据算了吧，总不能要求超图像国外GIS的那些软件商一样提供吧，难，其实像超图的webgl本身基于Cesium基础，如果能开源，他的iserver和桌面也许买得会更好




------------------ 原始邮件 ------------------
发件人: "fishelren"<notifications@github.com>; 
发送时间: 2019年5月16日(星期四) 中午1:40
收件人: "SuperMap/SuperMap-iEarth"<SuperMap-iEarth@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [SuperMap/SuperMap-iEarth] 公开地理数据来源从哪里获取？ (#17)




超图三维团队目前的很多数据也是经客户授权后才使用的，版权在客户，因此无法提供，望谅解~
