### ISSUE TITLE
怎么用Github吗？

### ISSUE THREAD

**Issue by EDsoft2018** [SuperMap/SuperMap-iEarth#18]
默认认为这个是超图官方的了，如果不是当我没说过。
发现一个很难受的事请？
一个项目，放上来，难道不是为了让大家交流吗？写这个的时候项目还没有下载完成。没看到src

wiki没有就算了， .md 也 没有，真是醉了。
基本说明。
帮助文档。
部署方案。
一个历史比阿里还悠久的公司！
对比阿里系的开源项目，差的不是技术，是态度。

还是说学不动了？？？？

**Comment by fishelren** [comment]
您好，你反馈的问题我们正在解决，会尽快补充相关文档，敬请期待！
