### ISSUE TITLE
@ispeco/authentication-sdk 包仓库查询不到

### ISSUE THREAD

**Issue by AbleCats** [SuperMap/SuperMap-iEarth#24]
@ispeco/authentication-sdk 请问这个包仓库是你们自己做的嘛？npm源和yarn源都没找到

**Comment by pasu** [comment]
已经删除，这个并不需要

**Comment by leaguecn** [comment]
最新的代码仍然没有移除，TM的害我把所有源都切换了一次，最后谷歌才发现是这个问题。
